### ISSUE TITLE
Warning deprecation in PHP 8

### ISSUE THREAD

**Issue by pabbec** [giauphan/laravel-qr-code#5]
`PHP Deprecated:  Optional parameter $filename declared before required parameter $foreColor is implicitly treated as a required parameter in vendor\giauphan\qr-code\src\QR_Code\Encoder\Vector.php on line 151`

This warning occurs in PHP >= 8

"Optional parameters specified before required parameters

An [optional parameter](https://www.php.net/manual/en/functions.arguments.php#functions.arguments.default) specified before required parameters is now always treated as required, even when called using [named arguments](https://www.php.net/manual/en/functions.arguments.php#functions.named-arguments). As of PHP 8.0.0, but prior to PHP 8.1.0, the below emits a deprecation notice on the definition, but runs successfully when called. As of PHP 8.1.0, an error of class [ArgumentCountError](https://www.php.net/manual/en/class.argumentcounterror.php) is thrown, as it would be when called with positional arguments."

### See:
https://www.php.net/manual/en/migration81.incompatible.php
https://php.watch/versions/8.0/deprecate-required-param-after-optional

### Potential solution (it's works for me):
Set a default value to $backColor and $foreColor parameters like vectSVG method. 

`public static function svg ($frame, $filename = false, int $pixelPerPoint = 4, int $outerFrame = 4, bool $saveAndPrint = false, int $backColor = 0xFFFFFF, int $foreColor = 0x000000) : void
`

**Comment by giauphan** [comment]
@pabbec Thank you for reporting this issue. I’ve updated the package release for ``laravel-qr-code`` to address this problem. Please update to the latest version and let me know if you encounter any further issues!

**Comment by pabbec** [comment]
Excellent! It's works! thanks!
